services:
  web:
    build:
      image: ${DOCKER_USERNAME}/landing:latest
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - staticfiles:/app/staticfiles
      - media:/app/media

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/static:ro
      - media:/media:ro

volumes:
  staticfiles:
  media:
