# Generated by Django 6.1.1 on 2026-09-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('rutube', 'RuTube'), ('yandex_disk', 'Yandex Disk'), ('google_drive', 'Google Drive')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('direct_download_link', models.URLField(blank=True, help_text='Direct download link for the external media.')),
            ],
            options={
                'verbose_name': 'External media',
                'verbose_name_plural': 'External media',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('media_kind', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], default='image', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Designates whether this media is the primary one for the associated object.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('external_media', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.externalmedia')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id', 'sort_order'], name='core_media_content_b1cce2_idx'),
        ),
    ]
