# Generated by Django 6.1.1 on 2026-09-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_externalmedia_media_delete_postmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
