# Generated by Django 6.1.1 on 2026-09-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteprofile_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_kind',
        ),
    ]
