# Generated by Django 6.1.1 on 2026-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_media_media_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_orientation',
            field=models.CharField(choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], default='horizontal', help_text='Controls the carousel aspect ratio and layout.', max_length=20),
        ),
    ]
