# Generated by Django 6.1.1 on 2026-09-16 08:07

from django.db import migrations, models


def remap_enum_values(apps, schema_editor):
    Post = apps.get_model('core', 'Post')
    ExternalMedia = apps.get_model('core', 'ExternalMedia')

    post_status_map = {
        'draft': 'd',
        'published': 'p',
        'archived': 'a',
    }
    carousel_orientation_map = {
        'horizontal': 'h',
        'vertical': 'v',
    }
    source_map = {
        'youtube': 'y',
        'rutube': 'r',
        'yandex_disk': 'yd',
        'google_drive': 'g',
    }

    for old_value, new_value in post_status_map.items():
        Post.objects.filter(status=old_value).update(status=new_value)

    for old_value, new_value in carousel_orientation_map.items():
        Post.objects.filter(carousel_orientation=old_value).update(carousel_orientation=new_value)

    for old_value, new_value in source_map.items():
        ExternalMedia.objects.filter(source=old_value).update(source=new_value)


def reverse_remap_enum_values(apps, schema_editor):
    Post = apps.get_model('core', 'Post')
    ExternalMedia = apps.get_model('core', 'ExternalMedia')

    post_status_map = {
        'd': 'draft',
        'p': 'published',
        'a': 'archived',
    }
    carousel_orientation_map = {
        'h': 'horizontal',
        'v': 'vertical',
    }
    source_map = {
        'y': 'youtube',
        'r': 'rutube',
        'yd': 'yandex_disk',
        'g': 'google_drive',
    }

    for old_value, new_value in post_status_map.items():
        Post.objects.filter(status=old_value).update(status=new_value)

    for old_value, new_value in carousel_orientation_map.items():
        Post.objects.filter(carousel_orientation=old_value).update(carousel_orientation=new_value)

    for old_value, new_value in source_map.items():
        ExternalMedia.objects.filter(source=old_value).update(source=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_carousel_orientation'),
    ]

    operations = [
        migrations.RunPython(remap_enum_values, reverse_remap_enum_values),
        migrations.AlterField(
            model_name='externalmedia',
            name='source',
            field=models.CharField(choices=[('y', 'YouTube'), ('r', 'RuTube'), ('yd', 'Yandex Disk'), ('g', 'Google Drive')], max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='carousel_orientation',
            field=models.CharField(choices=[('h', 'Горизонтальная'), ('v', 'Вертикальная')], default='h', help_text='Controls the carousel aspect ratio and layout.', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Черновик'), ('p', 'Опубликован'), ('a', 'Скрыт')], default='d', max_length=20),
        ),
    ]
