# Generated by Django 6.1.1 on 2026-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_externalmedia_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmedia',
            name='source',
            field=models.CharField(choices=[('y', 'YouTube'), ('r', 'RuTube'), ('vk', 'VK Video'), ('yd', 'Yandex Disk'), ('g', 'Google Drive')], max_length=32),
        ),
    ]
